version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clothing_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: clothing_db
    ports:
      - "5432:5432"